language: scala
scala:
  - 3.0.0-RC1
before_deploy:
  - sbt "docs / deployScript"
deploy:
  provider: pages:git
  edge: true
  target_branch: gh-pages
  local_dir: docs
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master